### PR TITLE
include CORS header with error responses

### LINKED ISSUE #12: CORS
haven't investigated this at all but it turns out the TODOs page of the demo app doesn't work in StackBlitz — might need to add CORS headers? https://twitter.com/SamVerschueren/status/1433064599444729859

### PR DESCRIPTION
**Pull request by Rich-Harris**
Closes #12

### CODE REVIEW

**Comment by lukeed** [comment]
If using the `prepare` lifecycle, you can apply global behavior. There's also a built-in CORS module that handles this all: https://github.com/lukeed/worktop/blob/master/examples/workers/cors/index.ts#L14

**Review by lukeed — APPROVED** [review]
I like to always add a maxage (for cache) but that's optional & your call

**Comment by Rich-Harris** [comment]
not sure I understand where that would go? i see `cache-control` mentioned in

```js
API.prepare = CORS.preflight({
	origin: '*', // allow any `Origin` to connect
	headers: ['Cache-Control', 'Content-Type', 'X-Count'],
	methods: ['GET', 'HEAD', 'PUT', 'POST', 'DELETE'],
});
```

but i don't understand where it's getting its value from, or what that has to do with `CORS`?

**Comment by lukeed** [comment]
It's CORS-related maxage option: https://github.com/lukeed/worktop/blob/master/src/cors.d.ts#L17

So that client can cache cors rules for X duration rather than always sending preflight

**Comment by Rich-Harris** [comment]
ah gotcha

**Pull request merged**
